---
- name: Debug Variable Merging
  hosts: all
  gather_facts: no
  tasks:
    - name: Show raw variables
      debug:
        msg: |
          === RAW VARIABLES ===
          Defaults:
          {{ _defaults | to_nice_yaml }}
          
          Vault Config:
          {{ _vault_config | to_nice_yaml }}
          
          Merged Result:
          {{ _merged_vars | to_nice_yaml }}
          
          === CONNECTION VARIABLES ===
          ansible_host: {{ ansible_host | default('Not set') }}
          ansible_user: {{ ansible_user | default('Not set') }}
          auth_method: {{ auth_method | default('Not set') }}
          ansible_become_pass: {{ 'SET' if ansible_become_pass is defined else 'NOT SET' }}

          
          === DEBUGGING ===
          Is vault_hosts defined? {{ vault_hosts is defined }}
          Current inventory_hostname: {{ inventory_hostname }}
          Host in vault? {{ inventory_hostname in vault_hosts if vault_hosts is defined else 'vault_hosts not defined' }}