---
- name: VPS Server Setup and Hardening (Multi-Host)
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/vault.yml
  serial: 1 # Deploy one host at a time

  pre_tasks:
    - name: Display current host information
      debug:
        msg: |
          === CONFIGURING HOST: {{ inventory_hostname }} ===
          Role: {{ server_role }}
          Environment: {{ environment_name }}
          OS Family: {{ ansible_os_family }}
          Authentication: {{ auth_method }}
          Target IP: {{ ansible_host }}
          Firewall Rules: {{ firewall_allow_ports | length }} allow rules, {{ firewall_deny_ports | length }} deny rules
          Role-Specific Ports: {{ role_specific_ports | length }} additional ports
          Custom Ports: {{ custom_firewall_ports | length }} custom ports

    - name: Check system requirements
      include_tasks: tasks/system_check.yml
      tags: [always]
      when: skip_system_check | default(false) == false

  roles:
    - role: system_setup
      tags: [system]
    - role: user_management
      tags: [users]
    - role: security_hardening
      tags: [security]
    - role: docker_setup
      tags: [docker]
    - role: firewall_setup
      tags: [firewall]
      when: server_role in ['coolify']
    - role: openvpn
      tags: [openvpn]
      #when: openvpn_enabled | default(false)
    - role: coolify
      tags: [coolify]
      when: server_role in ['coolify']
      
  post_tasks:
    - name: Run post-installation tests
      include_tasks: tasks/post_install_tests.yml
      tags: [tests]