---
- name: VPS Server Setup and Hardening
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/vault.yml
  serial: 1

  pre_tasks:
    - name: Display host information
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Role: {{ server_role }}
          OS: {{ ansible_os_family }}
          Firewall Rules: {{ firewall_rules | length }}

    - name: Check system requirements
      include_tasks: tasks/system_check.yml
      tags: [always]
      when: not (skip_system_check | default(false))

  roles:
    - role: system_setup
      tags: [system]
    - role: user_management
      tags: [users]
    - role: security_hardening
      tags: [security]
    - role: docker_setup
      tags: [docker]
    - role: firewall_setup
      tags: [firewall]
    - role: coolify
      tags: [coolify]
      when: server_role == 'coolify'
    - role: dokploy
      tags: [dokploy]
      when: server_role == 'dokploy'

  post_tasks:
    - name: Run post-installation tests
      include_tasks: tasks/post_install_tests.yml
      tags: [tests]