---
# Download and setup Coolify configuration files

- name: Download Coolify configuration files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0600'
    owner: 9999
    group: root
  loop:
    - { url: 'https://cdn.coollabs.io/coolify/docker-compose.yml', dest: '/data/coolify/source/docker-compose.yml' }
    - { url: 'https://cdn.coollabs.io/coolify/docker-compose.prod.yml', dest: '/data/coolify/source/docker-compose.prod.yml' }
    - { url: 'https://cdn.coollabs.io/coolify/.env.production', dest: '/data/coolify/source/.env' }

- name: Download Coolify upgrade script with execute permissions
  get_url:
    url: 'https://cdn.coollabs.io/coolify/upgrade.sh'
    dest: '/data/coolify/source/upgrade.sh'
    mode: '0700'
    owner: 9999
    group: root