
---

- name: Install locales package
  apt:
    name: locales
    state: present
    update_cache: yes

- name: Generate English locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set system locale to English
  copy:
    content: |
      LANG=en_US.UTF-8
      LANGUAGE=en_US:en
      LC_ALL=en_US.UTF-8
    dest: /etc/default/locale
    mode: '0644'
  notify: update locale

- name: Set locale environment variables
  lineinfile:
    path: /etc/environment
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    create: yes
  loop:
    - { key: 'LANG', value: 'en_US.UTF-8' }
    - { key: 'LANGUAGE', value: 'en_US:en' }
    - { key: 'LC_ALL', value: 'en_US.UTF-8' }

- name: Create locale profile script
  copy:
    content: |
      #!/bin/bash
      export LANG=en_US.UTF-8
      export LANGUAGE=en_US:en
      export LC_ALL=en_US.UTF-8
    dest: /etc/profile.d/locale.sh
    mode: '0644'

- name: Update locale for current session
  shell: |
    update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
    localectl set-locale LANG=en_US.UTF-8
  changed_when: false
  ignore_errors: yes

- name: Display locale configuration status
  debug:
    msg: |
      System locale set to English (en_US.UTF-8)
      Changes will take effect on next login or reboot
      Current session may still show previous locale
