
---
- name: Install essential packages (Debian/Ubuntu)
  apt:
    name:
      - curl
      - wget
      - git
      - htop
      - vim
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-pip
      - ufw
      - fail2ban
    state: present
    update_cache: yes

- name: Set up automatic security updates (Debian/Ubuntu)
  apt:
    name: unattended-upgrades
    state: present

- name: Configure automatic security updates (Debian/Ubuntu)
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades