
---
- name: restart ssh
  systemd:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
