
---
- name: Get system information
  setup:
    gather_subset:
      - hardware
      - network

- name: Check CPU cores
  fail:
    msg: "System has {{ ansible_processor_vcpus }} CPU cores, minimum required: {{ min_cpu_cores | int }}"
  when: ansible_processor_vcpus | int < min_cpu_cores | int

- name: Check memory
  fail:
    msg: "System has {{ (ansible_memtotal_mb / 1024) | round(1) }}GB RAM, minimum required: {{ min_memory_gb | int }}GB"
  when: (ansible_memtotal_mb | int / 1024) < (min_memory_gb | int)

- name: Display system information
  debug:
    msg: |
      === SYSTEM INFORMATION ===
      OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      Architecture: {{ ansible_architecture }}
      CPU Cores: {{ ansible_processor_vcpus }}
      Memory: {{ (ansible_memtotal_mb / 1024) | round(1) }}GB
      === REQUIREMENTS CHECK ===
      Required CPU Cores: {{ min_cpu_cores | int }}
      Required Memory: {{ min_memory_gb | int }}GB
      CPU Check: {{ 'PASS' if ansible_processor_vcpus | int >= min_cpu_cores | int else 'FAIL' }}
      Memory Check: {{ 'PASS' if (ansible_memtotal_mb | int / 1024) >= (min_memory_gb | int) else 'FAIL' }}
      Overall Status: {{ 'REQUIREMENTS MET' if (ansible_processor_vcpus | int >= min_cpu_cores | int) and ((ansible_memtotal_mb | int / 1024) >= (min_memory_gb | int)) else 'REQUIREMENTS NOT MET' }}
