
---
- name: Fetch GitHub webhook IPs (only if custom firewall is enabled)
  uri:
    url: https://api.github.com/meta
    method: GET
    return_content: yes
  register: github_meta
  delegate_to: localhost
  run_once: true
  when: enable_custom_firewall

- name: Set GitHub webhook IPs
  set_fact:
    github_webhook_ips: "{{ github_meta.json.hooks }}"
  when: enable_custom_firewall and github_meta is defined

- name: Configure UFW firewall (Debian/Ubuntu/Arch)
  include_tasks: ufw_setup.yml
  when: ansible_os_family in ["Debian", "Archlinux"]